### ISSUE TITLE
nodered - Error: EACCES: permission denied even though running under root 

### ISSUE THREAD

**Issue by z11aalex** [fragolinux/DockerIOT#2]
I am getting the following error, although  I run DockerIOT under root. Did I miss something in the readme?

```
nodered  | Error: EACCES: permission denied, copyfile '/usr/src/node-red/node_modules/node-red/settings.js' -> '/data/settings.js'
nodered  |     at Object.copyFileSync (node:fs:2847:3)
nodered  |     at copyFile (/usr/src/node-red/node_modules/fs-extra/lib/copy/copy-sync.js:64:6)
nodered  |     at onFile (/usr/src/node-red/node_modules/fs-extra/lib/copy/copy-sync.js:50:25)
nodered  |     at getStats (/usr/src/node-red/node_modules/fs-extra/lib/copy/copy-sync.js:42:44)
nodered  |     at Object.copySync (/usr/src/node-red/node_modules/fs-extra/lib/copy/copy-sync.js:32:10)
nodered  |     at Object.<anonymous> (/usr/src/node-red/node_modules/node-red/red.js:129:20)
nodered  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
nodered  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
nodered  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
nodered  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
nodered  |   errno: -13,
nodered  |   syscall: 'copyfile',
nodered  |   code: 'EACCES',
nodered  |   path: '/usr/src/node-red/node_modules/node-red/settings.js',
nodered  |   dest: '/data/settings.js'
nodered  | }
nodered  | node:internal/fs/utils:347
nodered  |     throw err;
nodered  |     ^
nodered  | 
nodered  | Error: EACCES: permission denied, copyfile '/usr/src/node-red/node_modules/node-red/settings.js' -> '/data/settings.js'
nodered  |     at Object.copyFileSync (node:fs:2847:3)
nodered  |     at copyFile (/usr/src/node-red/node_modules/fs-extra/lib/copy/copy-sync.js:64:6)
nodered  |     at onFile (/usr/src/node-red/node_modules/fs-extra/lib/copy/copy-sync.js:50:25)
nodered  |     at getStats (/usr/src/node-red/node_modules/fs-extra/lib/copy/copy-sync.js:42:44)
nodered  |     at Object.copySync (/usr/src/node-red/node_modules/fs-extra/lib/copy/copy-sync.js:32:10)
nodered  |     at Object.<anonymous> (/usr/src/node-red/node_modules/node-red/red.js:129:20)
nodered  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
nodered  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
nodered  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
nodered  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12) {
nodered  |   errno: -13,
nodered  |   syscall: 'copyfile',
nodered  |   code: 'EACCES',
nodered  |   path: '/usr/src/node-red/node_modules/node-red/settings.js',
nodered  |   dest: '/data/settings.js'
nodered  | }
root@raspberrypi:DockerIOT:12:54[0]> 
```

**Comment by Pat-78** [comment]
I had the same error.
I solved it with chmod 777 on the folder .../DockerIOT/nodered/data
